services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "True"
    ports:
      - "5341:80"
    networks:
      - "aspire"
  sql-probe:
    image: "${SQL_PROBE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SQL_PROBE_PORT}"
      ConnectionStrings__SqlServer: "Server=172.17.0.1,1433;Database=AdventureWorks2025;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      ConnectionStrings__seq: "http://seq:80"
    expose:
      - "${SQL_PROBE_PORT}"
    networks:
      - "aspire"
  rabbitmq:
    image: "docker.io/library/rabbitmq:4.2-management"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
    ports:
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - "aspire"
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${APISERVICE_PORT}"
      SQL_PROBE_HTTP: "http://sql-probe:${SQL_PROBE_PORT}"
      services__sql-probe__http__0: "http://sql-probe:${SQL_PROBE_PORT}"
      SQL_PROBE_HTTPS: "https://sql-probe:${SQL_PROBE_PORT}"
      ConnectionStrings__rabbitmq: "amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@rabbitmq:5672"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "${RABBIT_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBIT_PASSWORD}"
      RABBITMQ_URI: "amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@rabbitmq:5672"
      ConnectionStrings__SqlServer: "Server=172.17.0.1,1433;Database=AdventureWorks2025;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      ConnectionStrings__seq: "http://seq:80"
    ports:
      - "5320:8080"
      - "7196:8081"
    expose:
      - "${APISERVICE_PORT}"
    networks:
      - "aspire"
  rabbitconsumer:
    image: "${RABBITCONSUMER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${RABBITCONSUMER_PORT}"
      ConnectionStrings__rabbitmq: "amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@rabbitmq:5672"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "${RABBIT_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBIT_PASSWORD}"
      RABBITMQ_URI: "amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@rabbitmq:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      ConnectionStrings__seq: "http://seq:80"
    ports:
      - "5074:8080"
      - "7193:8081"
    expose:
      - "${RABBITCONSUMER_PORT}"
    networks:
      - "aspire"
  webfrontend:
    image: "${WEBFRONTEND_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${WEBFRONTEND_PORT}"
      APISERVICE_HTTP: "http://apiservice:${APISERVICE_PORT}"
      services__apiservice__http__0: "http://apiservice:${APISERVICE_PORT}"
      APISERVICE_HTTPS: "https://apiservice:${APISERVICE_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      ConnectionStrings__seq: "http://seq:80"
    ports:
      - "5070:${WEBFRONTEND_PORT}"
    depends_on:
      apiservice:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
