@MssqlProbe_ApiService_HostAddress = http://localhost:5133

GET {{MssqlProbe_ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MssqlProbe_ApiService_HostAddress}}/health/
Accept: application/json

###
